language: node_js
node_js:
- '0.10'
before_script:
- npm install
script:
- npm test
notifications:
  hipchat:
    rooms:
      secure: H+cseE+GxzkWcn5eC1tdAAKxQ/KBtRMmniJPnx1JGkEelV8yCLEReXEj9usR/bfXmwq2Syjum0Xq3R2dKtzrClvw+ZudYM6uOlVpdNfb/Mzv7AGz4p+mtRWSzPROfJIw6xbBdK2N2sXo2qH7qPBX6eey6ew2wiZ9XI0BRanAWUE=
