module.exports = {
    "0": "Success",
    "100": "Declined – No matching transaction",
    "101": "Declined – Cannot Void",
    "102": "Declined – Cannot Credit",
    "103": "Declined – Cannot Ticket",
    "104": "Declined",
    "105": "Declined - Over Limit",
    "106": "Declined - CVV2",
    "107": "Declined - Expired Card",
    "108": "Declined – Call",
    "109": "Declined – Pickup Card",
    "110": "Declined – Excessive Use",
    "111": "Declined – Invalid card",
    "112": "Declined – Invalid Expiration",
    "113": "Declined – Bank Unavailable",
    "114": "Declined – AVS",
    "117": "Declined – AVS",
    "123": "Declined – User Declined",
    "150": "Declined – AVS",
    "151": "Declined – CVV2",
    "152": "Declined – Invalid Ticket Amount",
    "154": "Declined – Integration Error",
    "156": "Declined – Unsupported CardType",
    "157": "Declined – Processor Risk",
    "200": "Declined – Scrub",
    "201": "Declined – Blocked",
    "208": "Declined – Duplicate Member ID",
    "209": "Declined – Duplicate Card",
    "210": "Declined – Duplicate Member Email",
    "211": "Declined - Exceeded Max Purchase Amount",
    "212": "Declined – Duplicate",
    "213": "Declined - Velocity Customer",
    "214": "Declined - Velocity Card #",
    "215": "Declined - Velocity Email",
    "216": "Declined – Iovation Decline",
    "217": "Declined - Velocity Email",
    "218": "Declined – Duplicate Member Device",
    "219": "Declined – 1Click Source",
    "220": "Declined – Too Many Cards",
    "221": "Declined – Affiliate Blocked",
    "222": "Declined – Trial Abuse",
    "300": "System Error - DNS Failure",
    "301": "System Error - Unable to Connect",
    "303": "System Error - Read Timeout",
    "311": "System Error - Bank Communications Error",
    "312": "System Error - Bank Communications Error",
    "313": "System Error - Bank Communications Error",
    "314": "System Error - Bank Communications Error",
    "315": "System Error - Bank Communications Error",
    "316": "System Error - Bank Communications Error",
    "321": "System Error - Bank Communications Error",
    "323": "System Error - Bank Communications Error",
    "325": "System Error - 3D Secure Error",
    "400": "Rejected - No Response Code",
    "403": "Rejected - Invalid Card Number",
    "404": "Rejected - Invalid Expiration",
    "405": "Rejected - Invalid Amount",
    "406": "Rejected - Invalid Merchant ID",
    "407": "Rejected - Invalid Merchant Account",
    "408": "Rejected - Incompatible Card Type",
    "409": "Rejected - No Suitable Account",
    "410": "Rejected - Invalid Transact ID",
    "411": "Rejected - Invalid Access Code",
    "412": "Rejected - Invalid Customer Data Length",
    "413": "Rejected - Invalid External Data Length",
    "414": "Rejected - Invalid Customer ID",
    "418": "Rejected - Invalid Currency",
    "419": "Rejected - Incompatible Currency",
    "420": "Rejected - Invalid Rebill Arguments",
    "436": "Rejected - Incompatible Descriptors",
    "438": "Rejected - Invalid Site ID",
    "441": "Rejected - Invoice ID Not Found",
    "443": "Rejected - Missing Customer ID",
    "444": "Rejected - Missing Name",
    "445": "Rejected - Missing Address",
    "446": "Rejected - Missing CVV",
    "448": "Rejected - No Active Membership",
    "449": "Rejected - Invalid CVV",
    "451": "Rejected - Invalid Clone Data",
    "452": "Rejected - Redundant Suspend or Resume"
};
